### ISSUE TITLE
Some Questions about the paper

### ISSUE THREAD

**Issue by 123456789asdfjkl** [Westlake-AI/MogaNet#6]
Hi！Thank you for your great work！我对高亮的这段话没能理解，想请教您，这个应该如何理解
![image](https://user-images.githubusercontent.com/45223476/221727726-b9b9ea8c-034a-47b9-8709-7bfaa9168d95.png)

**Comment by Lupin1998** [comment]
Hi, @123456789asdfjkl, thanks for your excellent question! Unfortunately, there is also a typo, and it should be `0-order interaction of each patch itself and 'n-order' interaction covering all patches`. Given an image of n patches, the m-order interactions are defined by Eq.1 and Eq. 2 in [Representation Bottleneck](https://arxiv.org/abs/2111.06236), where $0\ge m\le n-2$. There are two trivial conditions: (a) When the interaction pair i,j is the same patch, it will be 0-order interaction that the patch interacts with itself, i.e., $Conv_{1\times 1}(\cdot)$. (b) When all patches are pooled into a single token, e.g., by global average pooling GAP($\cdot$), it cannot be measured by the concept of m-order interaction (because the contextual set cannot be larger than m-2). Therefore, modelling two trivial conditions by $Conv_{1\times 1}(\cdot)$ and GAP($\cdot$), the proposed FD module can intend to help the model learn more useful interactions.

![image](https://user-images.githubusercontent.com/44519745/221776874-5a83f827-51cf-4e1b-8fa7-9ae6b6df43d6.png)
![image](https://user-images.githubusercontent.com/44519745/221777047-150a0a1a-02cb-4f88-84fb-97a143d356bc.png)

**Comment by 123456789asdfjkl** [comment]
我明白了，感谢您的解答
