### ISSUE TITLE
How do I create an interference code

### ISSUE THREAD

**Issue by silber60** [Westlake-AI/MogaNet#9]
I'd like to make an interference code. 

I'm trying to create an interference code, but I keep getting this error: "EncoderDecoder: 'MogaNet_feat is not in the models registry'.

It doesn't go back to the mmsegmentation demo code, so please.

**Comment by Lupin1998** [comment]
Hi, @silber60, thanks for using MogaNet! I am sorry for the late reply because of the NeurIPS submission deadline. I have provided the demo of semantic segmentation as MMSegmentation in [demo](https://github.com/Westlake-AI/MogaNet/blob/main/segmentation/demo) in the latest commit, and you can try it in Jupyter Notebook. I hope this can be helpful to you.

**Comment by Lupin1998** [comment]
Hi, if there are no more questions, I will close this issue.
